INSERT INTO peliculas (titulo, director, anio) VALUES
('El Gran Escape', 'John Smith', 2022),
('Viaje al Futuro', 'Jane Doe', 2019, 'I'),
('La Aventura Espacial', 'Alan Smithee', 2021, 'A'),
('El Misterio del Lago', 'Sandra Lee', 2018, 'A'),
('Historias de la Noche', 'Tim Burton', 2020, 'I'),
('El Reino Perdido', 'Chris Evans', 2017, 'A'),
('Amor en París', 'Sofia Coppola', 2016, 'A'),
('El Último Guerrero', 'James Cameron', 2015, 'I'),
('Sueños de Libertad', 'Steven Spielberg', 2014, 'A'),
('La Tierra Prometida', 'Ridley Scott', 2013, 'A'),
('Horizontes Lejanos', 'Peter Jackson', 2012, 'I'),
('El Valle Encantado', 'Guillermo del Toro', 2023, 'A'),
('Retorno al Pasado', 'Martin Scorsese', 2022, 'A'),
('Navegando Estrellas', 'Quentin Tarantino', 2021, 'I'),
('El Bosque Prohibido', 'David Fincher', 2020, 'A'),
('Cazadores de Sombras', 'Christopher Nolan', 2019, 'A'),
('Un Día en la Vida', 'Richard Linklater', 2018, 'I'),
('El Puente de Cristal', 'Wes Anderson', 2017, 'A'),
('Fantasmas del Pasado', 'M. Night Shyamalan', 2016, 'A'),
('La Ciudad Oculta', 'J.J. Abrams', 2015, 'I');
