#especifica que se usará el protocolo jdbc:postgresql, el servidor esta en el localhost (la misma maquina), y el puerto es el 5432 (el puerto estandar de PostgreSQL), y la base de datos a la que se debe conectar es Red_Social

spring.datasource.url=jdbc:postgresql://localhost:5432/social_red

#configura el nombre de usuario (postgres) que se utilizara para conectarse a la base de datos

spring.datasource.username=postgres

#configura la ckave asociada al usuario que se utilizara para conectarse a la base de datos

spring.datasource.password=12345

#establece el nombre de la aplicacion Spring Boot como "seguridad"
spring.application.name=seguridad

#especifica que se debe utilizar el controlador JDBC de postgreSQL para interactuar con una base de datos, informando a spring como debe conectarse y comunicarse con una base de datos PostgreSQL especifica

spring.datasource.driver-class-name=org.postgresql.Driver

#deshabilita la gestion automatica del esquema de la base de datospor parte de Hibernate. Esto significa que Hibernate no realizara ninguna operacion de lenguaje de definicion de datos (DDL) como crear, actualizar validar tablas al iniciar la aplicacion; el esquema de la base de datos debe ser gestionado manualmente

spring.jpa.hibernate.ddl-auto=none

#le dice a spring y a hibernate como generar el codigo SQL optimo y las interacciones de persistencia especificas para la base de datos PostgreSQL, asegurando que el codigo de la aplicacion pueda interactuar correctamente con ella sin necesidad de cambios

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE